// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import TagifyController from "./tagify_controller"
application.register("hello", HelloController)
application.register("tagify", TagifyController)

import StarFilterController from "./star_filter_controller"
application.register("star-filter", StarFilterController)

import RangeOrderController from "./range_order_controller"
application.register("range-order", RangeOrderController)

import BulkFormController from "./bulk_form_controller"
application.register("bulk-form", BulkFormController)
